#!/bin/bash
############################################################
# Set variables                                            #
############################################################

UBUNTU_VERSION="crops/yocto:ubuntu-20.04-base"
KAS_BRANCH="master"
YOCTO_VERSION="honister"

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Help output ."
   echo
   echo "Syntax: ./better-kas-container [-r|b|h|f]"
   echo "options:"
   echo "r     Run the container"
   echo "b     Build."
   echo "h     Print this Help."
   echo "v     Print kas version for this script."
   echo
}

version ()
{
       # Display Versions

   echo  KAS_BRANCH:$KAS_BRANCH
   echo  UBUNTU_VERSION=$UBUNTU_VERSION
   echo  YOCTO_VERSION=$YOCTO_VERSION
}


#build_function
build_function()
{

set -e
sed -i "s/USER.*/USER=$USER/g" .env
sed -i "s/UID.*/UID=$UID/g" .env
sed -i "s/GID.*/GID=$(id -g)/g" .env
docker compose build

}

# run function
run_function () 
{
set -e
docker compose up -d 
docker exec -it kas-container-v1 /bin/bash
}

safety_lock () 
{
       # Display Warning
   echo "if you have old build please move it out of this directory "
   echo
   echo "then move it back as this scripts removes all dirs"
   echo "recreate them with the right permissions "

    while true ;do 
    read -p "If you are sure that you want to continue, write yes " yn
    case $yn in 
    [Yy]* ) continue; break ;;
    [Nn]* ) exit ;;
    *) echo "write yes or no to exit"
    esac
done
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################

#force_get_kas
#safety_lock




while getopts ":rbhfv" option; do 
    case $option in 
    r)
        run_function
        exit;;
    b)
        build_function
        exit;;
    h)
        Help
        exit;;          
    v)
        version
        exit;;
    esac
done


