version: "3.8"

services:
  better-kas-container:
    #image: crops/yocto:ubuntu-20.04-base
    container_name: better-kas-container-v1
    build:
      context: ./
      dockerfile: Dockerfile
      args :
        - USER=$USER
        - UID=$UID
        - GID=$GID
    #command: /bin/bash
    tty: true
    user: '${USER}'
    volumes:
      - $HOME:$HOME