

services:
  better-kas-container:
    #image: crops/yocto:ubuntu-20.04-base
    container_name: better-kas-container-v1
    build:
      context: ./
      dockerfile: Dockerfile
      args :
        - BKC_USER=$BKC_USER
        - BKC_UID=$BKC_UID
        - BKC_GID=$BKC_GID
    command: /bin/bash
    tty: true
    user: '${USER}'
    volumes:
      - $HOME:$HOME
