name: Docker Image CI

on:
  push:
    branches: [ "honister" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./better-kas-container -b
    - name: Test run the Docker image
      run: ./better-kas-container -r